#!/usr/bin/env bash
# ============================================================
# audit-orphan-tables.sh — Story 22.8 (T1 + T2 audit)
# ============================================================
# Audita 3 tabelas suspeitas órfãs (discovery §5):
#   - pending_student_assignments
#   - notification_queue
#   - alert_history
#
# Outputs:
#   - docs/22.8-orphan-audit.md
#
# Como rodar:
#   export PGHOST=... PGPORT=... PGUSER=... PGPASSWORD=... PGDATABASE=...
#   bash scripts/audit-orphan-tables.sh
# ============================================================

set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

: "${PGHOST:=}"
: "${PGPORT:=5432}"
: "${PGDATABASE:=postgres}"
: "${PGUSER:=postgres}"

AUDIT_FILE="docs/22.8-orphan-audit.md"
TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

PSQL_OPTS="-h ${PGHOST} -p ${PGPORT} -U ${PGUSER} -d ${PGDATABASE} -v ON_ERROR_STOP=0 -t -A"

TABLES=(pending_student_assignments notification_queue alert_history)

echo "==== audit-orphan-tables.sh START ${TS} ===="

mkdir -p docs

cat > "${AUDIT_FILE}" <<HEADER
# Story 22.8 — Orphan Tables Audit

Generated: ${TS}
Source: \`scripts/audit-orphan-tables.sh\`

Tabelas auditadas: \`pending_student_assignments\`, \`notification_queue\`, \`alert_history\`

---

HEADER

for tbl in "${TABLES[@]}"; do
  echo "[audit] ${tbl}..."

  cat >> "${AUDIT_FILE}" <<EOF
## Table: \`${tbl}\`

### 1. Grep refs em codebase

**supabase/functions/:**
\`\`\`
$(grep -rn "${tbl}" supabase/functions/ 2>/dev/null | head -10 || echo "0 matches")
\`\`\`

**supabase/migrations/:**
\`\`\`
$(grep -rn "${tbl}" supabase/migrations/ 2>/dev/null | head -10 || echo "0 matches")
\`\`\`

**admin/ js/:**
\`\`\`
$(grep -rn "${tbl}" admin/ js/ 2>/dev/null | head -10 || echo "0 matches")
\`\`\`

EOF

  if [[ -n "${PGHOST}" ]] && pg_isready -h "${PGHOST}" -p "${PGPORT}" >/dev/null 2>&1; then
    cat >> "${AUDIT_FILE}" <<EOF
### 2. DB stats (rows + last_write)

\`\`\`
$(PGPASSWORD="${PGPASSWORD:-}" psql ${PSQL_OPTS} -c "
SELECT
  count(*) AS total_rows,
  (SELECT max(created_at) FROM public.${tbl}) AS last_created_at,
  (SELECT count(*) FROM public.${tbl} WHERE created_at > now() - interval '90 days') AS rows_last_90d,
  (SELECT count(*) FROM public.${tbl} WHERE created_at > now() - interval '7 days') AS rows_last_7d
FROM public.${tbl};
" 2>/dev/null || echo "Query falhou — tabela pode não existir ou ${tbl} tem schema diferente")
\`\`\`

### 3. Schema

\`\`\`
$(PGPASSWORD="${PGPASSWORD:-}" psql ${PSQL_OPTS} -c "
SELECT column_name, data_type, is_nullable, column_default
  FROM information_schema.columns
 WHERE table_schema='public' AND table_name='${tbl}'
 ORDER BY ordinal_position;
" 2>/dev/null || echo "schema query falhou")
\`\`\`

### 4. Triggers + Constraints

\`\`\`
$(PGPASSWORD="${PGPASSWORD:-}" psql ${PSQL_OPTS} -c "
SELECT trigger_name, event_manipulation, action_timing
  FROM information_schema.triggers
 WHERE event_object_schema='public' AND event_object_table='${tbl}';
" 2>/dev/null || echo "trigger query falhou")
\`\`\`

EOF
  else
    cat >> "${AUDIT_FILE}" <<EOF
### 2-4. DB queries skipped (PG not reachable)

Run com PGHOST setado pra capturar stats.
EOF
  fi

  cat >> "${AUDIT_FILE}" <<EOF

### 5. Decisão (preencher manualmente)

- [ ] **Keep** — Active. Justificar consumer + adicionar COMMENT ON TABLE.
- [ ] **Deprecate** — Rename \`${tbl}_deprecated_$(date +%Y%m%d)\` + trigger Slack alert se write.
- [ ] **Drop** — Snapshot antes + DROP migration (após 1 sprint deprecated).

**Razão:** _preencher após review_

---

EOF
done

cat >> "${AUDIT_FILE}" <<EOF
## Sumário decisional

| Tabela | Refs codebase | Rows totais | Rows 90d | Decisão | ADR ref |
|--------|---------------|-------------|----------|---------|---------|
| pending_student_assignments | (TBD) | (TBD) | (TBD) | (TBD) | ADR-026 |
| notification_queue | (TBD) | (TBD) | (TBD) | (TBD) | ADR-026 |
| alert_history | (TBD) | (TBD) | (TBD) | (TBD) | ADR-026 |

## Próximos passos

1. Review manual deste audit
2. Para cada tabela: decidir keep/deprecate/drop
3. Atualizar \`docs/architecture/ADR-026-orphan-tables-cleanup.md\` com decisões
4. Criar migration baseada em decisões (separada por tabela ou consolidada)
5. Atualizar \`docs/architecture/schema.md\` com mapa final

Generated by audit-orphan-tables.sh
EOF

echo ""
echo "==== audit-orphan-tables.sh END ===="
echo "Output: ${AUDIT_FILE}"
echo ""
echo "Próximo: review manual + preencher ADR-026 decisões"
